name: Sync to Main Pressure Perfect Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to ariangibson/pressureperfect
        run: |
          git remote add parent https://x-access-token:${{ secrets.PRESSURE_PERFECT_MAIN_REPO_TOKEN }}@github.com/ariangibson/pressureperfect.git
          git push parent HEAD:main --force
